#!/bin/sh
#
# /etc/rc.d/wlan: start/stop wireless interface
#

case $1 in
	start)
		/etc/rc.d/wpa_supplicant start
		/etc/rc.d/dhcpcd start
		;;
	stop)
		/etc/rc.d/dhcpcd stop
		/etc/rc.d/wpa_supplicant stop
		;;
	restart)
		/etc/rc.d/wpa_supplicant restart
		/etc/rc.d/dhcpcd restart
		;;
	status)
		/etc/rc.d/wpa_supplicant status
		/etc/rc.d/dhcpcd status
		;;
	*)
		echo "Usage: $0 [start|stop|restart|status]"
		;;
esac

# End of file
